# Generated by Django 4.0.2 on 2022-02-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('userId', models.IntegerField()),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('body', models.TextField(max_length=400)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewerapp.posts')),
            ],
        ),
    ]
