# Generated by Django 4.0.2 on 2022-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(),
        ),
    ]
