# Generated by Django 4.0.2 on 2022-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewerapp', '0002_alter_comments_body_alter_posts_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=220),
        ),
    ]
