# Generated by Django 4.0.2 on 2022-02-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewerapp', '0003_alter_comments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
